service: aws-node-http-api-project
plugins:
  - serverless-bundle
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  profile: kelsusinc
  iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - appconfig:StartConfigurationSession
      - appconfig:GetLatestConfiguration
    Resource: '*'

functions:
  hello:
    handler: config.main
    layers:
      - arn:aws:lambda:us-east-1:027255383542:layer:AWS-AppConfig-Extension:61
    events:
      - httpApi:
          path: /
          method: get
